// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7kk2hOqV72E7c0rk6F-f0bIKyLeny6Tc',
    appId: '1:79150003785:web:b7125de11dbd2024e5b198',
    messagingSenderId: '79150003785',
    projectId: 'fitara-ai-3fe36',
    authDomain: 'fitara-ai-3fe36.firebaseapp.com',
    storageBucket: 'fitara-ai-3fe36.firebasestorage.app',
    measurementId: 'G-5MHDR65Z3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtjoU8MOiOUl1lUG8w_-sOw5_hCuLPngU',
    appId: '1:79150003785:android:0e3b649e0ae34a13e5b198',
    messagingSenderId: '79150003785',
    projectId: 'fitara-ai-3fe36',
    storageBucket: 'fitara-ai-3fe36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNgtBFt8UdnioUtoyh3KnNxQ9-TrR0NG4',
    appId: '1:79150003785:ios:06d74962e1c62eabe5b198',
    messagingSenderId: '79150003785',
    projectId: 'fitara-ai-3fe36',
    storageBucket: 'fitara-ai-3fe36.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNgtBFt8UdnioUtoyh3KnNxQ9-TrR0NG4',
    appId: '1:79150003785:ios:06d74962e1c62eabe5b198',
    messagingSenderId: '79150003785',
    projectId: 'fitara-ai-3fe36',
    storageBucket: 'fitara-ai-3fe36.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7kk2hOqV72E7c0rk6F-f0bIKyLeny6Tc',
    appId: '1:79150003785:web:784181ae12bb5ef6e5b198',
    messagingSenderId: '79150003785',
    projectId: 'fitara-ai-3fe36',
    authDomain: 'fitara-ai-3fe36.firebaseapp.com',
    storageBucket: 'fitara-ai-3fe36.firebasestorage.app',
    measurementId: 'G-F3LNXP7BMJ',
  );
}
